### PR TITLE
Import braces from __future__

### PR DESCRIPTION
**Pull request by PythonProdigy**
I propose we use C-style braces here to denote scope instead of white space, its cleaner for this particular script.

### CODE REVIEW

**Comment by mjhea0** [comment]
@PythonProdigy why is this cleaner? Why would you ever want to use curly braces like that?

**Comment by PythonProdigy** [comment]
The C language first appeared 43 years ago. It's one of the most brilliant technological achievements of modern society. Dennis Ritchie may have passed away in late 2011, but I've still held the C language near and dear to my heart. Every morning I grab a cup of tea and sit down with my laptop to browse for particular python repositories on GitHub. I've come to find a lot of joy in your samples and thought we could still show Python programmers the beauty of C in this small script, by using braces to denote scope instead of whitespace. 

Martin Fowler once said, "Any fool can write code that a computer can understand. Good programmers write code that humans can understand". Sometimes my deep love for C (ANSI, not that other trash) gets in the way of the opinions of others. 

I will mention if anyone is interested in C they should check out this book: http://www.amazon.com/The-Programming-Language-Brian-Kernighan/dp/0131103628. K&R is *the definitive standard* for learning C.

You have carte blanche on this as it is your project, thanks for your consideration.

**Comment by mjhea0** [comment]
I have no problem with C, but Python is about whitespace. That defines the scope, not braces like C or JavaScript.

**Comment by PythonProdigy** [comment]
You raise a good point, Michael. 

I have just finished reading the [Zen of Python](https://www.python.org/dev/peps/pep-0020/) and I now realize that my request was extremely out of line, and quite offensive to any Python fans out there. I profusely apologize for my lack of thought prior to opening this pull request...and for the sake of my sanity I hope we can all forget it happened.

I dream that one day there will be a language that combines the simplicity of python with the beautifully subtle crudeness of C that I've grown to love so much. I thought Python could be that language but it looks like it's not quite ready to fill those shoes.

**Comment by mjhea0** [comment]
No worries. I appreciate the discussion. Cheers!

**Pull request closed without merging**
